name: Create changelog and bump version based on commit history

on: workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.matrix.outputs.packages }}
    steps:
      - uses: actions/checkout@v4
      - id: matrix
        run: |
          echo 'packages=['$(ls packages | sed -r -z  -e "s/([a-z]+)\n/\"\1\", /g" -e "s/, $//")']' >> "$GITHUB_OUTPUT"

  changelog:
    needs: ["setup"]
    strategy:
      max-parallel: 1
      matrix:
        package: ${{ fromJSON(needs.setup.outputs.packages) }}

    uses: ./.github/workflows/changelog.yml
    with:
      package-name: ${{ matrix.package }}

  tags:
    needs: ["setup", "changelog"]
    strategy:
      max-parallel: 1
      matrix:
        package: ${{ fromJSON(needs.setup.outputs.packages) }}
    uses: ./.github/workflows/tag.yml
    with:
      package-name: ${{ matrix.package }}
