name: Generate a changelog

on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string

jobs:
  changelog:
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{steps.cliff.outputs.content}}
      version: ${{steps.cliff.outputs.version}}
      is-changed: ${{steps.changed.outputs.is-changed}}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate a changelog
        id: cliff
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: --verbose --include-path "packages/${{inputs.package-name}}/**/*" --bump --tag-pattern "^@casablanca-css/${{inputs.package-name}}@v[0-9].*"
        env:
          OUTPUT: packages/${{inputs.package-name}}/CHANGELOG.md

      - name: Diff
        id: diff
        run: |
          git add -N .
          git diff --name-only --exit-code
        continue-on-error: true

      - name: Set changed status
        id: changed
        run: echo "is-changed=${{ steps.diff.outcome == 'failure' }}" >> "$GITHUB_OUTPUT"

  version:
    needs: ["changelog"]
    uses: ./.github/workflows/version.yml
    if: ${{ fromJson(needs.changelog.outputs.is-changed) }}
    with:
      package-name: ${{ inputs.package-name }}
      version: ${{ needs.changelog.outputs.version }}
      content: ${{ needs.changelog.outputs.changelog }}
