name: Create changelog and tags based on commit history

on: workflow_dispatch

jobs:
  changelog:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        package: [core, styled, utils]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate a changelog
        id: changelog
        uses: ./.github/workflows/changelog.yml
        with:
          package-name: ${{ matrix.package }}

      - name: Create tags
        id: tag
        uses: ./.github/workflows/tag.yml
        if: ${{ steps.changelog.outputs.is-changed == 'true' }}
        with:
          package-name: ${{ matrix.package }}
          version: ${{ steps.changelog.outputs.version }}
