name: Create a new tag

on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: git pull

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Set git config
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Get package.json
        id: package
        run: |
          echo "package<<EOF" >> "$GITHUB_OUTPUT"
          cat packages/${{ inputs.package-name }}/package.json >> "$GITHUB_OUTPUT"
          echo EOF >> "$GITHUB_OUTPUT"

      - name: Get package version
        id: version
        run: echo "version=${{ fromJson(steps.package.outputs.package).version }}" >> "$GITHUB_OUTPUT"

      - name: Find tag
        id: find
        run: echo "tag=$(git tag -l "@casablanca-css/${{ inputs.package-name }}@v${{ steps.version.outputs.version }}" | wc -l)" >> "$GITHUB_OUTPUT"

      - name: Create tag
        if: ${{ steps.find.outputs.tag == 0 }}
        run: git tag "@casablanca-css/${{ inputs.package-name }}@v${{ steps.version.outputs.version }}"

      - name: Push to origin
        run: |
          git push origin "@casablanca-css/${{ inputs.package-name }}@v${{ steps.version.outputs.version }}"
