name: Bump package version

on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      version:
        required: true
        type: string
      content:
        required: true
        type: string

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.RELEASER_APP_ID }}
          private-key: ${{ secrets.RELEASER_APP_KEY }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - run: npm ci

      - name: Set git config
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Write changelog content
        run: |
          cat << 'EOF' > packages/${{inputs.package-name}}/CHANGELOG.md
          ${{ inputs.content }}
          EOF

      - name: Set package version
        run: npm -w packages/${{ inputs.package-name }} version ${{ inputs.version }} --workspaces-update=false

      - name: Update ${{ inputs.package-name }} version in other packages
        run: |
          npm run set-deps-version -- ${{ inputs.package-name }} ${{ inputs.version }}
          npx syncpack format

      - name: Commit files
        run: |
          git add --all
          git commit --message 'Set `${{ inputs.package-name }}` version ${{ inputs.version }}' --all --no-verify

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
