name: Bump package version

on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      version:
        required: true
        type: string
      content:
        required: true
        type: string

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - run: npm ci

      - name: Set git config
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Write changelog content
        run: |
          cat << 'EOF' > packages/${{inputs.package-name}}/CHANGELOG.md
          ${{ inputs.content }}
          EOF

      - name: Set package version
        run: npm -w packages/${{ inputs.package-name }} version ${{ inputs.version }} --workspaces-update=false

      - name: Update ${{ inputs.package-name }} version in other packages
        run: |
          npm run set-deps-version -- ${{ inputs.package-name }} ${{ inputs.version }}
          npx syncpack format

      - name: Commit and push updates
        run: |
          git add -N .
          git commit -m "Set `${{ inputs.package-name }}` version ${{ inputs.version }}"
          git push origin
